name: UcanLIVE
favicon: null
layout_spectrum: 0.67672
typography_spectrum: 0.25204049958847463
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0000ce'
    - '#6b6be2'
    - '#fe2100'
    - '#fec300'
  brandStrength: 0.375
  lightness: 0.625
  saturation: 0.7192589160986245
  rhythmicContrast: 0.75
purpose: []
